---
title: "data cleaning"
output: html_document
---


# Import Data

```{r}
library(readr)
library(janitor)
music <- read_csv("~/Documents/EDA/tcc_ceds_music.csv")%>%
  clean_names()
View(music)
```

# Checking Assertions
```{r}
library(tidyverse)
library(assertr)
library(corrplot)


#initial exploration of variables
class(music)

music%>%
  summarise(min(release_date), max(release_date))

#check that values are between 0-1 for acousticness, instrumentalness, valence, energy, and age
music%>%
  assert(within_bounds(0,1), acousticness:energy)%>%
  assert(within_bounds(0,1), age)

#check for NAs
music%>%
  assert(not_na, artist_name:age)

```

# Remove Unwanted Variables after Checking Correlations

```{r}

```

# Change Characteristic Types to Numeric Types for Variables
```{r}
music$valence = as.numeric(music$valence)
music$energy = as.numeric(music$energy)
```

# check for NAs
```{r}
music = na.omit(music)
#Min-Max Scaling 
normalize <- function(x) {
return ((x - min(x)) / (max(x) - min(x)))
}

Length_norm=normalize(music$len)

music<- music %>%
  mutate(Length_norm)
```


# checking correlations
```{r}

music <- music %>% 
  mutate(id = 1) %>% 
  mutate(id = cumsum(id))
head(music)

new_t <- music %>% 
  select(dating:energy)
colnames(new_t)

new_t$valence = as.numeric(new_t$valence)
new_t$energy = as.numeric(new_t$energy)

# scatterplot matrix of the audio feature parameters
corrplot(cor(new_t))

```
# remove unwanted variables & capitalize column names 
```{r}
music_cleaned<-music%>%
  select(id, artist_name:len, danceability:Length_norm)

rename_with(music_cleaned, toupper)

```





In variable 'topic', there are several possible wrong/useless types.
```{r}
unique(tcc_ceds_music$topic)

tcc_ceds_music_cleaned = tcc_ceds_music_cleaned %>%
  filter(topic == "sadness"|topic == "world/life"|topic == "music"|topic == "romantic"|topic == "violence"|topic == "obscene"|topic == "night/time"|topic == "feelings")
```



